version: 0.1.0.{build}
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
image: Visual Studio 2017
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
nuget:
  disable_publish_on_pr: true
build_script:
- cmd: >-
    cd src

    dotnet build

    dotnet pack
deploy:
- provider: NuGet
  server: https://www.myget.org/F/jajo/api/v2/package
  api_key:
    secure: tzue+2xgeOeKXndBjAJcMot+aFlWLa4fcsAajvcnq3ogfA2Mwd5NZrgzNXuMkh4d
  skip_symbols: true
  artifact: /.*\.nupkg/
  on:
    branch: master